//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 通用审批模板明细:通用审批模板明细
    /// </summary>
    public partial class ApproveTemplateDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ApproveTemplateDetail()
        {
            this.ApproveLog = new HashSet<ApproveLog>();
        }
    
    	/// <summary>
    	/// ID
    	/// </summary>
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 模板ID
    	/// </summary>
    	public System.Guid TemplateID { get; set; }
    	/// <summary>
    	/// 流程环节序号
    	/// </summary>
    	public int Rank { get; set; }
    	/// <summary>
    	/// 环节名称
    	/// </summary>
    	public string RankName { get; set; }
    	/// <summary>
    	/// 通过后环节
    	/// </summary>
    	public Nullable<int> PassRank { get; set; }
    	/// <summary>
    	/// 通过后状态
    	/// </summary>
    	public string PassState { get; set; }
    	/// <summary>
    	/// 拒绝后环节
    	/// </summary>
    	public int RejectRank { get; set; }
    	/// <summary>
    	/// 拒绝后状态
    	/// </summary>
    	public string RejectState { get; set; }
    	public System.Guid RoleID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ApproveLog> ApproveLog { get; set; }
        public virtual ApproveTemplate ApproveTemplate { get; set; }
        public virtual Role Role { get; set; }
    }
}
