//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommonWords
    {
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 常用词缩写
    	/// </summary>
    	public string CommonID { get; set; }
    	/// <summary>
    	/// 常用词完整
    	/// </summary>
    	public string CommonNo { get; set; }
    	/// <summary>
    	/// 常用词名称
    	/// </summary>
    	public string CommonName { get; set; }
    	/// <summary>
    	/// 说明
    	/// </summary>
    	public string Remark { get; set; }
    }
}
