//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceMainHist
    {
    	public System.Guid PK { get; set; }
    	public System.Guid ID { get; set; }
    	public string InterfaceNo { get; set; }
    	public string BelongSystem { get; set; }
    	public string BelongModule { get; set; }
    	public string Operation { get; set; }
    	public string InExample { get; set; }
    	public string OutExample { get; set; }
    	public string Parameter { get; set; }
    	public string Remark { get; set; }
    	public Nullable<int> IsDeleted { get; set; }
    	public Nullable<System.Guid> CreateUserID { get; set; }
    	public Nullable<System.DateTime> CreateDate { get; set; }
    	public string Flag { get; set; }
    }
}
