//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceDetail
    {
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 接口编号(传自主表)
    	/// </summary>
    	public Nullable<System.Guid> InterfaceID { get; set; }
    	/// <summary>
    	/// 参数编码
    	/// </summary>
    	public string ParameterNo { get; set; }
    	/// <summary>
    	/// 参数名称
    	/// </summary>
    	public string ParameterName { get; set; }
    	/// <summary>
    	/// 类型
    	/// </summary>
    	public string ParameterType { get; set; }
    	/// <summary>
    	/// 最大长度
    	/// </summary>
    	public Nullable<int> ParameterLen { get; set; }
    	/// <summary>
    	/// 是否必填
    	/// </summary>
    	public Nullable<int> IsNull { get; set; }
    
        public virtual InterfaceMain InterfaceMain { get; set; }
    }
}
