//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceDetailHist
    {
    	public System.Guid PK { get; set; }
    	public System.Guid ID { get; set; }
    	public System.Guid InterfaceID { get; set; }
    	public string ParameterNo { get; set; }
    	public string ParameterName { get; set; }
    	public string ParameterType { get; set; }
    	public Nullable<int> ParameterLen { get; set; }
    	public Nullable<int> IsNull { get; set; }
    	public string Flag { get; set; }
    }
}
