//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class InterfaceMain
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public InterfaceMain()
        {
            this.InterfaceDetail = new HashSet<InterfaceDetail>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 接口编码
    	/// </summary>
    	public string InterfaceNo { get; set; }
    	/// <summary>
    	/// 所属系统
    	/// </summary>
    	public string BelongSystem { get; set; }
    	/// <summary>
    	/// 所属模块
    	/// </summary>
    	public string BelongModule { get; set; }
    	/// <summary>
    	/// 操作类型
    	/// </summary>
    	public string Operation { get; set; }
    	/// <summary>
    	/// 输入参数
    	/// </summary>
    	public string InExample { get; set; }
    	/// <summary>
    	/// 输出参数
    	/// </summary>
    	public string OutExample { get; set; }
    	/// <summary>
    	/// 举例
    	/// </summary>
    	public string Parameter { get; set; }
    	/// <summary>
    	/// 说明
    	/// </summary>
    	public string Remark { get; set; }
    	/// <summary>
    	/// 是否删除
    	/// </summary>
    	public Nullable<int> IsDeleted { get; set; }
    	/// <summary>
    	/// 创建人
    	/// </summary>
    	public Nullable<System.Guid> CreateUserID { get; set; }
    	/// <summary>
    	/// 创建日期
    	/// </summary>
    	public Nullable<System.DateTime> CreateDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<InterfaceDetail> InterfaceDetail { get; set; }
    }
}
