//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 组织架构表
    /// </summary>
    public partial class Organization
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Organization()
        {
            this.Organization1 = new HashSet<Organization>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 组织架构名称
    	/// </summary>
    	public string Name { get; set; }
    	/// <summary>
    	/// 组织架构类型
    	/// </summary>
    	public string Type { get; set; }
    	/// <summary>
    	/// 父级Id
    	/// </summary>
    	public Nullable<System.Guid> ParentID { get; set; }
    	/// <summary>
    	/// 排序
    	/// </summary>
    	public int Sort { get; set; }
    	/// <summary>
    	/// 名称路径
    	/// </summary>
    	public string Path { get; set; }
    	/// <summary>
    	/// ID路径
    	/// </summary>
    	public string IdPath { get; set; }
    	/// <summary>
    	/// 通用组织ID
    	/// </summary>
    	public Nullable<System.Guid> GeneralID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization> Organization1 { get; set; }
        public virtual Organization Organization2 { get; set; }
        public virtual OrganizationGeneral OrganizationGeneral { get; set; }
        public virtual Role Role { get; set; }
    }
}
