//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 通用组织
    /// </summary>
    public partial class OrganizationGeneral
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrganizationGeneral()
        {
            this.Organization = new HashSet<Organization>();
        }
    
    	/// <summary>
    	/// 编号
    	/// </summary>
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 名称
    	/// </summary>
    	public string Name { get; set; }
    	/// <summary>
    	/// 类型
    	/// </summary>
    	public string Type { get; set; }
    	/// <summary>
    	/// 说明
    	/// </summary>
    	public string Description { get; set; }
    	/// <summary>
    	/// 分组
    	/// </summary>
    	public string Group { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Organization> Organization { get; set; }
    }
}
