//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 功能类型表
    /// </summary>
    public partial class PermissionGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionGroup()
        {
            this.PermissionBtn = new HashSet<PermissionBtn>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 类型名称
    	/// </summary>
    	public string Name { get; set; }
    	/// <summary>
    	/// 应用Id
    	/// </summary>
    	public System.Guid ApplicationID { get; set; }
    	/// <summary>
    	/// 父级Id
    	/// </summary>
    	public Nullable<System.Guid> ParentID { get; set; }
    	/// <summary>
    	/// 排序
    	/// </summary>
    	public int Sort { get; set; }
    	/// <summary>
    	/// ID路径
    	/// </summary>
    	public string IdPath { get; set; }
    	/// <summary>
    	/// 名称路径
    	/// </summary>
    	public string Path { get; set; }
    	public string Description { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionBtn> PermissionBtn { get; set; }
    }
}
