//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 权限按钮表
    /// </summary>
    public partial class PermissionBtn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionBtn()
        {
            this.PermissionBtnInterface = new HashSet<PermissionBtnInterface>();
            this.PermissionBtnRole = new HashSet<PermissionBtnRole>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 按钮名称
    	/// </summary>
    	public string ButtonName { get; set; }
    	/// <summary>
    	/// 窗体名称
    	/// </summary>
    	public string FormName { get; set; }
    	/// <summary>
    	/// 显示名称
    	/// </summary>
    	public string DisplayName { get; set; }
    	public System.Guid ApplicationID { get; set; }
    	public System.Guid PermissionGroupID { get; set; }
    	/// <summary>
    	/// 无权限时操作方式：禁用，隐藏
    	/// </summary>
    	public string NoPermissionType { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual PermissionGroup PermissionGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionBtnInterface> PermissionBtnInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionBtnRole> PermissionBtnRole { get; set; }
    }
}
