//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 权限接口表
    /// </summary>
    public partial class PermissionInterface
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PermissionInterface()
        {
            this.PermissionBtnInterface = new HashSet<PermissionBtnInterface>();
            this.PermissionInterfaceRole = new HashSet<PermissionInterfaceRole>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 名称
    	/// </summary>
    	public string Name { get; set; }
    	/// <summary>
    	/// 应用Id
    	/// </summary>
    	public System.Guid ApplicationID { get; set; }
    	/// <summary>
    	/// 控制器名称
    	/// </summary>
    	public string ControllerName { get; set; }
    	/// <summary>
    	/// 方法名称
    	/// </summary>
    	public string MethodName { get; set; }
    	/// <summary>
    	/// 动作名称
    	/// </summary>
    	public string ActionName { get; set; }
    	/// <summary>
    	/// 参数验证:（?参数名=参数值&参数名=参数值）
    	/// </summary>
    	public string QueryString { get; set; }
    	public string Description { get; set; }
    
        public virtual Application Application { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionBtnInterface> PermissionBtnInterface { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PermissionInterfaceRole> PermissionInterfaceRole { get; set; }
    }
}
