//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户表
    /// </summary>
    public partial class User
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public User()
        {
            this.UserToken = new HashSet<UserToken>();
            this.UserToRole = new HashSet<UserToRole>();
        }
    
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 账号
    	/// </summary>
    	public string Account { get; set; }
    	/// <summary>
    	/// 密码
    	/// </summary>
    	public string Password { get; set; }
    	/// <summary>
    	/// 名称
    	/// </summary>
    	public string Name { get; set; }
    	/// <summary>
    	/// 创建时间
    	/// </summary>
    	public System.DateTime CreateTime { get; set; }
    	/// <summary>
    	/// 签名
    	/// </summary>
    	public byte[] Signature { get; set; }
    	/// <summary>
    	/// 指纹
    	/// </summary>
    	public byte[] Fingerprint { get; set; }
    	/// <summary>
    	/// 指纹备用
    	/// </summary>
    	public byte[] FingerprintSpare { get; set; }
    	public int IsDeleted { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToken> UserToken { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserToRole> UserToRole { get; set; }
    }
}
