//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// 用户登录令牌表
    /// </summary>
    public partial class UserToken
    {
    	public System.Guid ID { get; set; }
    	/// <summary>
    	/// 用户Id
    	/// </summary>
    	public System.Guid UserID { get; set; }
    	/// <summary>
    	/// 应用Id
    	/// </summary>
    	public System.Guid ApplicationID { get; set; }
    	public string Token { get; set; }
    	/// <summary>
    	/// 更新时间
    	/// </summary>
    	public System.DateTime UpdateTime { get; set; }
    	public System.Guid UsingApplicationID { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Application Application1 { get; set; }
        public virtual User User { get; set; }
    }
}
