//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient
    /// </summary>
    public partial class V_PermissionBtnQuery
    {
    	public System.Guid ID { get; set; }
    	public string ButtonName { get; set; }
    	public string FormName { get; set; }
    	public string DisplayName { get; set; }
    	public System.Guid ApplicationID { get; set; }
    	public System.Guid PermissionGroupID { get; set; }
    	public string ApplicationName { get; set; }
    	public string PermissionGroupName { get; set; }
    	public string PermissionGroupPath { get; set; }
    	public string PermissionGroupIdPath { get; set; }
    	public int Sort { get; set; }
    }
}
