//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient
    /// </summary>
    public partial class V_PermissionInterfaceQuery
    {
    	public System.Guid ID { get; set; }
    	public string Name { get; set; }
    	public System.Guid ApplicationID { get; set; }
    	public string ControllerName { get; set; }
    	public string MethodName { get; set; }
    	public string ActionName { get; set; }
    	public string QueryString { get; set; }
    	public string Description { get; set; }
    	public string AName { get; set; }
    }
}
