//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Enssi.Authenticate.Data
{
    using System;
    using System.Collections.Generic;
    
    /// <summary>
    /// System.Data.SqlClient
    /// </summary>
    public partial class V_UserToRoleQuery
    {
    	public System.Guid ID { get; set; }
    	public System.Guid UserID { get; set; }
    	public System.Guid RoleID { get; set; }
    	public string Account { get; set; }
    	public string Password { get; set; }
    	public string UserName { get; set; }
    	public System.DateTime CreateTime { get; set; }
    	public string RoleName { get; set; }
    	public string Description { get; set; }
    	public string Path { get; set; }
    	public string IdPath { get; set; }
    }
}
